
# Configurações do projeto
aoi:
  # Caixa da Corrente do Golfo / Sargaços (lon_min, lat_min, lon_max, lat_max)
  bbox: [-80.0, 25.0, -60.0, 40.0]

time:
  start: "2025-09-20"
  end:   "2025-09-30"

datasets:
  sst_short_name: "MUR-JPL-L4-GLOB-v4.1"   # GHRSST / MUR L4 (PO.DAAC)
  modis_l3_chl_short_name: "MODISA_L3m_CHL_NRT"  # Aqua MODIS L3 Mapped CHL (NRT)
  modis_resolution: "4km"
  # PACE OCI L2 OC products variam; usaremos busca por palavras-chave:
  pace_l3_chl_short_name: "PACE_OCI_L3M_CHL_NRT"

  pace_l4_moana_short_name: "PACE_OCI_L4M_MOANA_NRT"
  pace_resolution: "4km"
  ecco_short_name: "ECCO_L4_OCEAN_VEL_05DEG_DAILY_V4R4"  # Daily u/v currents (PO.DAAC)
  # SWOT: L2 Low Rate Sea Surface Height (expert/basic); usamos short_name conhecido:
  swot_short_name: "SWOT_L2_LR_SSH_Unsmoothed_D"

processing:
  grid_resolution_deg: 0.1     # ~10km
  max_granules_per_source: 50  # para protótipo
  random_seed: 42

model:
  algorithm: "xgboost"
  top_percent_for_hit: 20



